# Introduction to NumPy and Pandas

## What is NumPy?

NumPy is a package in Python used for powerful, scalable computation. NumPy has a special array object that allows it store data in a smaller memory size and have faster access/edit times than ordinary Python list objects. It also has a large number of useful mathematical functions for linear algebra, fourier transforms, etc. We're going to mainly focus on the array objects today.

## Installation of Packages
Before we dive into Numpy, we need to first install the package and then import it. First, you want to make sure that you have pip3 installed. This is a tool that makes it really easy to install the numerous packages that are found on the Python Package Index. Chances are that your computer already has pip installed but you need pip3, since we're working in Python 3. 

Go to your terminal and type:

```terminal
sudo easy_install pip

```
After you enter your login password, you have successfully installed the most recent version of pip and pip3! Now anytime you want to install a package, you type in the terminal: 

```terminal
pip3 install insert_package_name_here
```
Or if you just want to do it within the Jupyter Notebook, just type: 
```terminal
!pip3 install insert_package_name_here
```
Try installing 'numpy' on your own!

## Importing Packages

You only have to install a new package once using terminal. However, the package is not automatically added into your program; you need to first import it. We are going to import NumPy's contents into our program. Anytime we use a NumPy array or methods, we can call it using an abbreviated name like np instead of typing the whole name (numpy). 

In [2]:
# Note that there is no output when you import a package
import numpy as np

## NumPy Arrays
The NumPy array is a homogeneous, multidimensional array. Let's break that down. 

## INSERT PIC OF NUMPY ARRAY VS. PYTHON LIST

1. Homogeneous 
    * Every element in a NumPy array is of the same datatype. 
        * The result is that you can save much more memory than storing the data in a List
    * They can be all integers, all floats, or all strings. 
    * What happens if there's a mix of datatypes in your NumPy array? 
        * You'll experiment shortly and see what happens.


2. Multidimensional
    * You can have 1D NumPy arrays, 2D NumPy matrices, and more! 
    * Multidimensional NumPy arrays are much more easy to work with than multidimensional Python Lists, as you will see

3. Array
    * An array is an ordered group of elements stored in contiguous memory. 
    * Python actually does not have a native array data structure. 
        * Python only has lists which have its elements scattered all across memory!
    * NumPy arrays have their elements stored in one continuous block of memory. 
        * The result is much faster access to elements!
        
For more information on how Numpy Arrays work "under the hood" check out its [documentation](https://docs.scipy.org/doc/numpy/reference/internals.html)

Let's actually get started!

## Creating a NumPy Array

In [30]:
# There are many ways to create an array! 

# Creating an array from a list
lis = [[1,2,3],[4,5,6]]
arr = np.array(lis)
print(arr)
print(type(arr))

print("\n")  # \n creates a new line break

# Or creating an array using the arange function.
arr2 = np.arange(8)
print(arr2)
arr2 = np.arange(1, 9)
print(arr2)
arr2 = np.arange(1, 9, 2) 
print(arr2)

print("\n")
# The shape of a 2D array is the number of rows by the number of columns in an array. 

# The shape is a property of a NumPy array object.
# That means you can get its value by the dot notation or a function
print("The shape of a 2D array is " + str(arr.shape))
# In the last print statement, substitute 'arr.shape' for 'np.shape(arr)'

# If we want to change the shape of an array, we can use the reshape function.
arr2 = np.arange(1,9).reshape(2,4)
print(arr2)
print("\n")


# You can use the zeros function to create an array of place-holder zeros with a certain shape
arr3 = np.zeros((3,5))
print(arr3)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]
[1 3 5 7]


The shape of a 2D array is (2, 3)
[[1 2 3 4]
 [5 6 7 8]]


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


### Explore:
 Use the next cell to briefly experiment with the shape of different 1D arrays and 3D arrays. 
 Also figure out what the properties 'size' and 'ndim' do without looking it up on the documentation. 